<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Empleados.aspx.cs" Inherits="Menu_Home" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Mr. Develover - ADMIN</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="../css/reset.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="../css/layout.css" type="text/css" media="screen" />
    <link href="admstyle1.css" rel="stylesheet" type="text/css" media="screen" />

    <script src="../js/jquery-1.6.3.min.js"></script>
    <script src="../js/cufon-yui.js"></script>
    <script src="../js/cufon-replace.js"></script>
    <script src="../js/NewsGoth_BT_400.font.js"></script>
    <script src="../js/FF-cash.js"></script>
    <script src="../js/script.js"></script>
    <script src="../js/jquery.equalheights.js"></script>
    <script src="../js/jquery.easing.1.3.js"></script>
    <script src="../js/tms-0.3.js"></script>
    <script src="../js/tms_presets.js"></script>
    <script src="../js/easyTooltip.js"></script>



</head>
<body id="page1">
    <form id="Form1" runat="server">
        <div class="extra">
            <div class="main">

                <!--==============================header=================================-->

                <header>
                    <div class="indent">
                        <div class="row-top">
                            <div class="wrapper">
                                <h1><a href="HomeA.aspx">MR.Develever</a><asp:Label ID="Identidad" runat="server" Text="" Font-Size="Larger"></asp:Label></h1>
                                <strong class="support">
                                    <asp:Label ID="Label1" runat="server" Text=""> </asp:Label><asp:Button ID="btnLogout" runat="server" Text="Log out" OnClick="btnLogout_Click" CssClass="button-2" /></strong>
                            </div>
                        </div>
                        <nav>
                            <ul class="menu">
                                <li><a href="HomeA.aspx">Inicio</a></li>
                                <%--                                <li><a href="PF.aspx">Perfil</a></li>--%>
                                <li><a href="Clientes.aspx">Clientes</a></li>
                                <li><a class="active" href="Empleados.aspx">Empleados</a></li>
                                <li><a href="Solicitudes.aspx">Solicitudes</a></li>
                                <li class="last"><a href="ServiciosA.aspx">Servicios</a></li>
                            </ul>
                        </nav>
                    </div>
                </header>
                <!--==============================aside================================-->
                <!--==============================content================================-->
                <div>
                    <h3 class="p1" style="padding-left:40px;">Lista de Empleados</h3>
                    <br />
                    <asp:Label ID="Label2" runat="server" Text="Por Empresa: "></asp:Label>
                    <asp:DropDownList ID="DropEmpresa" runat="server" DataSourceID="Empresa" DataTextField="Empresa" DataValueField="id_Empresa" AutoPostBack="True"></asp:DropDownList>

                    <asp:SqlDataSource ID="Empresa" runat="server" ConnectionString="<%$ ConnectionStrings:HelpDeskConnectionString %>" SelectCommand="SELECT [id_Empresa], [Empresa] FROM [Empresas]"></asp:SqlDataSource>
                </div>

                <div>
                    <br />
                    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="id_Empleado" DataSourceID="Empleados" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" CellPadding="10" CellSpacing="4" ForeColor="Black" GridLines="Vertical">
                        <AlternatingRowStyle BackColor="White" />
                        <Columns>
                            <asp:BoundField DataField="id_Empleado" HeaderText="IDEmpleado" InsertVisible="False" ReadOnly="True" SortExpression="id_Empleado" />
                            <asp:BoundField DataField="Nombres" HeaderText="Nombres" SortExpression="Nombres" />
                            <asp:BoundField DataField="Apellidos" HeaderText="Apellidos" SortExpression="Apellidos" />
                            <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                            <asp:BoundField DataField="Usuario" HeaderText="Usuario" SortExpression="Usuario" />
                            <asp:BoundField DataField="Fecha_Creacion" HeaderText="Fecha Creacion" SortExpression="Fecha_Creacion" />
                            <asp:BoundField DataField="id_admin" HeaderText="ID admin" SortExpression="id_admin" />
                            <asp:BoundField DataField="id_Puesto" HeaderText="ID Puesto" SortExpression="id_Puesto" />
                        </Columns>
                        <FooterStyle BackColor="#CCCC99" />
                        <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
                        <RowStyle BackColor="#F7F7DE" />
                        <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
                        <SortedAscendingCellStyle BackColor="#FBFBF2" />
                        <SortedAscendingHeaderStyle BackColor="#848384" />
                        <SortedDescendingCellStyle BackColor="#EAEAD3" />
                        <SortedDescendingHeaderStyle BackColor="#575357" />
                    </asp:GridView>
                     

                    <asp:SqlDataSource ID="Empleados" runat="server" ConnectionString="<%$ ConnectionStrings:HelpDeskConnectionString %>" SelectCommand="SELECT [id_Empleado], [Nombres], [Apellidos], [Email], [Usuario], [Fecha_Creacion], [id_admin], [id_Puesto] FROM [Empleados] WHERE ([id_Empresa] = @id_Empresa AND [id_Empleado] <>6)" 
                        DeleteCommand="DELETE FROM [Empleados] WHERE [id_Empleado]=@id_empleado" UpdateCommand="UPDATE [Empleados] SET [Nombres]=@nombres, [Apellidos]=@apellidos, [Email]=@email, [Usuario]=@usuario, [id_Puesto]=@id_puesto WHERE [id_Empleado]=@id_empleado">
                        <SelectParameters>
                            <asp:ControlParameter ControlID="DropEmpresa" Name="id_Empresa" PropertyName="SelectedValue" Type="Int32" />
                        </SelectParameters>
                    </asp:SqlDataSource>
                     

                </div>
                <br />
                <div>
                    <h3 class="p1" style="padding-left:40px;">Agregar Empleado</h3>
                    <br />
                    <div>
                        <asp:Label ID="Label3" runat="server" Text="Nombres: "></asp:Label>
                        <asp:TextBox ID="txtNombres" runat="server"></asp:TextBox>

                        <asp:Label ID="Label4" runat="server" Text="Apellidos: "></asp:Label>
                        <asp:TextBox ID="txtApellidos" runat="server"></asp:TextBox>

                        <asp:Label ID="Label5" runat="server" Text="Puesto: "></asp:Label>
                        <asp:DropDownList ID="DropPuestos" runat="server" DataSourceID="PuestosTrabajo" DataTextField="Puesto" DataValueField="id_Puesto"></asp:DropDownList>

                        <asp:Label ID="Label6" runat="server" Text="Email: "></asp:Label>
                        <asp:TextBox ID="txtEmail" runat="server"></asp:TextBox>

                        <asp:Label ID="Label7" runat="server" Text="Empresa: "></asp:Label>
                        <asp:DropDownList ID="DropEmpresa2" runat="server" DataSourceID="Empresa" DataTextField="Empresa" DataValueField="id_Empresa"></asp:DropDownList>

                        <asp:Label ID="Label8" runat="server" Text="Usuario: "></asp:Label>
                        <asp:TextBox ID="txtUsaurio" runat="server"></asp:TextBox>

                        <asp:Label ID="Label9" runat="server" Text="Contraseña: "></asp:Label>
                        <asp:TextBox ID="txtContrasena" TextMode="Password" runat="server"></asp:TextBox>

                        <asp:Button ID="btnCancelarE" runat="server" Text="Cancelar" CssClass="button-2" OnClick="btnCancelarE_Click" />
                        <asp:Button ID="btnGuardarE" runat="server" Text="Guardar" CssClass="button-2" OnClick="btnGuardarE_Click" />
                    </div>
                </div>

                <br />
                <div>
                    <h3 class="p1" style="padding-left:40px;">Lista de Puestos de Trabajo</h3>
                    <br />
                    <div>
                        <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" DataKeyNames="id_Puesto" DataSourceID="PuestosTrabajo" Width="379px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" CellPadding="10" CellSpacing="4" ForeColor="Black" GridLines="Vertical">
                            <AlternatingRowStyle BackColor="White" />
                            <Columns>
                                <asp:BoundField DataField="id_Puesto" HeaderText="ID Puesto" InsertVisible="False" ReadOnly="True" SortExpression="id_Puesto" />
                                <asp:BoundField DataField="Puesto" HeaderText="Puesto" SortExpression="Puesto" />
                            </Columns>
                            <FooterStyle BackColor="#CCCC99" />
                            <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
                            <RowStyle BackColor="#F7F7DE" />
                            <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
                            <SortedAscendingCellStyle BackColor="#FBFBF2" />
                            <SortedAscendingHeaderStyle BackColor="#848384" />
                            <SortedDescendingCellStyle BackColor="#EAEAD3" />
                            <SortedDescendingHeaderStyle BackColor="#575357" />
                        </asp:GridView>

                        <asp:SqlDataSource ID="PuestosTrabajo" runat="server" ConnectionString="<%$ ConnectionStrings:HelpDeskConnectionString %>" SelectCommand="SELECT * FROM [Puestos]" 
                            DeleteCommand="DELETE FROM [Puestos] WHERE [id_Puesto]=@id_puesto" UpdateCommand="UPDATE [Puestos] SET [Puesto]=@puesto WHERE [id_Puesto]=@id_puesto"></asp:SqlDataSource>

                    </div>
                    <br />
                    <div>
                        <h3 class="p1" style="padding-left:40px;">Agregar Puestos de Trabajo</h3>
                        <br />
                        <div>
                            <asp:Label ID="Label10" runat="server" Text="Nuevo Puesto de Trabjo: "></asp:Label>
                            <asp:TextBox ID="txtNuevoPuesto" runat="server"></asp:TextBox>

                            <asp:Button ID="btnCancelarP" runat="server" Text="Cancelar" CssClass="button-2" OnClick="btnCancelarP_Click" />
                            <asp:Button ID="btnGuardarP" runat="server" Text="Guardar" CssClass="button-2" OnClick="btnGuardarP_Click" />

                        </div>
                    </div>


                </div>
                <asp:Label ID="AdminID" runat="server" Text="" Visible="false"></asp:Label>
                <!--==============================footer=================================-->
                <footer>
                    <div class="main">
                        <div class="footer-bg">
                            <p class="prev-indent-bot">Copyright &copy; <a href="#">Milton</a> Todos los derechos Reservados | Diseñado por <a target="_blank" href="http://www.templatemonster.com/">www.mr.developer.com</a></p>
                            <ul class="list-services">
                                <li><a class="tooltips" href="#"></a></li>
                                <li class="item-1"><a class="tooltips" href="#"></a></li>
                                <li class="item-2"><a class="tooltips" href="#"></a></li>
                            </ul>
                        </div>
                    </div>
                </footer>
    </form>
</body>
</html>
