<%@ Page Language="C#" AutoEventWireup="true" CodeFile="ServiciosA.aspx.cs" Inherits="Menu_Home" MaintainScrollPositionOnPostback="true" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Mr. Develover - ADMIN</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="../css/reset.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="../css/layout.css" type="text/css" media="screen" />
    <link href="admstyle1.css" rel="stylesheet" type="text/css" media="screen" />

    <script src="../js/jquery-1.6.3.min.js"></script>
    <script src="../js/cufon-yui.js"></script>
    <script src="../js/cufon-replace.js"></script>
    <script src="../js/NewsGoth_BT_400.font.js"></script>
    <script src="../js/FF-cash.js"></script>
    <script src="../js/script.js"></script>
    <script src="../js/jquery.equalheights.js"></script>
    <script src="../js/jquery.easing.1.3.js"></script>
    <script src="../js/tms-0.3.js"></script>
    <script src="../js/tms_presets.js"></script>
    <script src="../js/easyTooltip.js"></script>



</head>
<body id="page1">
    <form id="Form1" runat="server">
        <div class="extra">
            <div class="main">

                <!--==============================header=================================-->

                <header>
                    <div class="indent">
                        <div class="row-top">
                            <div class="wrapper">
                                <h1><a href="HomeA.aspx">MR.Develever</a><asp:Label ID="Identidad" runat="server" Text="" Font-Size="Larger"></asp:Label></h1>
                                <strong class="support">
                                    <asp:Label ID="Label1" runat="server" Text=""> </asp:Label><asp:Button ID="btnLogout" runat="server" Text="Log out" OnClick="btnLogout_Click" CssClass="button-2" /></strong>
                            </div>
                        </div>
                        <nav>
                            <ul class="menu">
                                <li><a href="HomeA.aspx">Inicio</a></li>
                                <%--                                <li><a href="PF.aspx">Perfil</a></li>--%>
                                <li><a href="Clientes.aspx">Clientes</a></li>
                                <li><a href="Empleados.aspx">Empleados</a></li>
                                <li><a href="Solicitudes.aspx">Solicitudes</a></li>
                                <li class="last"><a class="active" href="ServiciosA.aspx">Servicios</a></li>
                            </ul>
                        </nav>
                    </div>
                </header>
                <!--==============================aside================================-->
                <!--==============================content================================-->
                <div>
                    <h3 class="p1" style="padding-left: 40px;">Lista de Servicios</h3>
                    <br />
                    <div style="padding-left: 60px">
                        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="id_Servicio" DataSourceID="ListaServicios" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" CellPadding="10" CellSpacing="4" ForeColor="Black" GridLines="Vertical">
                            <AlternatingRowStyle BackColor="White" />
                            <Columns>
                                <asp:BoundField DataField="id_Servicio" HeaderText="id_Servicio" InsertVisible="False" ReadOnly="True" SortExpression="id_Servicio" />
                                <asp:BoundField DataField="Descripcion" HeaderText="Descripcion" SortExpression="Descripcion" />
                            </Columns>
                            <FooterStyle BackColor="#CCCC99" />
                            <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
                            <RowStyle BackColor="#F7F7DE" />
                            <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
                            <SortedAscendingCellStyle BackColor="#FBFBF2" />
                            <SortedAscendingHeaderStyle BackColor="#848384" />
                            <SortedDescendingCellStyle BackColor="#EAEAD3" />
                            <SortedDescendingHeaderStyle BackColor="#575357" />
                        </asp:GridView>
                        <asp:SqlDataSource ID="ListaServicios" runat="server" ConnectionString="<%$ ConnectionStrings:HelpDeskConnectionString %>" SelectCommand="SELECT * FROM [TiposServicios]"
                            DeleteCommand="DELETE FROM [TiposServicios] WHERE [id_Servicio]=@id_servicio" UpdateCommand="UPDATE [TiposServicios] SET [Descripcion]=@Descripcion WHERE [id_Servicio]=@id_servicio"></asp:SqlDataSource>
                    </div>
                    <br />
                    <div>
                        <h3 class="p1" style="padding-left: 40px;">Agregar un Servicio</h3>
                        <br />
                        <div>
                            <span style="padding-left: 50px">
                                <asp:Label ID="Label2" runat="server" Text="Tipo de Servicio: " Font-Size="Large"></asp:Label></span>
                            <asp:TextBox ID="txtTipoServicio" runat="server" Width="300px" Height="25px"></asp:TextBox>
                            <asp:Button ID="btnCancelar" runat="server" Text="Cancelar" CssClass="button-2" OnClick="btnCancelar_Click" />
                            <asp:Button ID="btnGuardar" runat="server" Text="Guardar" CssClass="button-2" OnClick="btnGuardar_Click" />
                        </div>
                    </div>

                </div>
                <br />
                <div>
                    <h3 class="p1" style="padding-left: 40px;">Lista de Empresas</h3>
                    <br />
                    <div>
                        <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" DataKeyNames="id_Empresa" DataSourceID="ListaEmpresas" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" CellPadding="10" CellSpacing="4" ForeColor="Black" GridLines="Vertical">
                            <AlternatingRowStyle BackColor="White" />
                            <Columns>
                                <asp:BoundField DataField="id_Empresa" HeaderText="id_Empresa" InsertVisible="False" ReadOnly="True" SortExpression="id_Empresa" />
                                <asp:BoundField DataField="Empresa" HeaderText="Empresa" SortExpression="Empresa" />
                                <asp:BoundField DataField="Direccion" HeaderText="Direccion" SortExpression="Direccion" />
                                <asp:BoundField DataField="Telefono" HeaderText="Telefono" SortExpression="Telefono" />
                                <asp:BoundField DataField="RNC" HeaderText="RNC" SortExpression="RNC" />
                                <asp:BoundField DataField="id_admin" HeaderText="id_admin" SortExpression="id_admin" />
                                <asp:BoundField DataField="Fecha_Creacion" HeaderText="Fecha_Creacion" SortExpression="Fecha_Creacion" />
                            </Columns>
                            <FooterStyle BackColor="#CCCC99" />
                            <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
                            <RowStyle BackColor="#F7F7DE" />
                            <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
                            <SortedAscendingCellStyle BackColor="#FBFBF2" />
                            <SortedAscendingHeaderStyle BackColor="#848384" />
                            <SortedDescendingCellStyle BackColor="#EAEAD3" />
                            <SortedDescendingHeaderStyle BackColor="#575357" />
                        </asp:GridView>
                        <asp:SqlDataSource ID="ListaEmpresas" runat="server" ConnectionString="<%$ ConnectionStrings:HelpDeskConnectionString %>" SelectCommand="SELECT [id_Empresa], [Empresa], [Direccion], [Telefono], [RNC], [id_admin], [Fecha_Creacion] FROM [Empresas]"
                            DeleteCommand="DELETE FROM [Empresas] WHERE [id_Empresa]=@id_empresa" UpdateCommand="UPDATE [Empresas] SET [Empresa]=@empresa, [Direccion]=@direccion, [Telefono]=@telefono WHERE [id_Empresa]=@id_empresa"></asp:SqlDataSource>
                    </div>
                    <br />
                    <div>
                        <h3 class="p1" style="padding-left: 40px;">Agregar una Empresa</h3>
                        <br />
                        <div style="padding-bottom:20px">
                            <span style="padding-left: 50px">
                                <asp:Label ID="Label3" runat="server" Text="Empresa:" Font-Size="Large"></asp:Label>
                                <asp:TextBox ID="txtEmpresa" runat="server" Width="250px" Height="25px"></asp:TextBox></span>

                            <span style="padding-left: 50px">
                                <asp:Label ID="Label4" runat="server" Text="Dirección:" Font-Size="Large"></asp:Label>
                                <asp:TextBox ID="txtDireccion" runat="server" Width="250px" Height="25px"></asp:TextBox></span>
                        </div>
                        <span style="padding-left: 50px">
                            <asp:Label runat="server" Text="Teléfono:" Font-Size="Large"></asp:Label>
                            <asp:TextBox ID="txtTelefono" runat="server" Width="250px" Height="25px"></asp:TextBox></span>

                        <span style="padding-left:50px">
                            <asp:Label ID="Label5" runat="server" Text="RNC:" Font-Size="Large"></asp:Label>
                            <asp:TextBox ID="txtRNC" runat="server" Width="250px" Height="25px"></asp:TextBox></span>
                        
                        <div style="padding-left: 600px; padding-top:30px">
                            <asp:Button ID="btnCancelarP" runat="server" Text="Cancelar" CssClass="button-2" OnClick="btnCancelarP_Click" />

                            <asp:Button ID="btnGuardarP" runat="server" Text="Guardar" CssClass="button-2" OnClick="btnGuardarP_Click" />
                        </div>
                        <br />
                    </div>
                </div>
                <asp:Label ID="AdminID" runat="server" Text="" Visible="false"></asp:Label>
                <!--==============================footer=================================-->
                <footer>
                    <div class="main">
                        <div class="footer-bg">
                            <p class="prev-indent-bot">Copyright &copy; <a href="#">Mr. Developer</a> Todos los derechos Reservados | Diseñado por <a target="_blank" href="http://www.templatemonster.com/">www.mr.developer.com</a></p>
                            <ul class="list-services">
                                <li><a class="tooltips" href="#"></a></li>
                                <li class="item-1"><a class="tooltips" href="#"></a></li>
                                <li class="item-2"><a class="tooltips" href="#"></a></li>
                            </ul>
                        </div>
                    </div>
                </footer>
    </form>
</body>
</html>
